sulu_media:
    format_cache:
        save_image: '%env(bool:MEDIA_SAVE_IMAGE_LOCAL)%'

    format_manager:
        default_imagine_options:
            # a value between 95 and 75 is recommended
            # see also: https://docs.sulu.io/en/2.5/book/image-formats.html
            jpeg_quality: 95
            webp_quality: 95
            avif_quality: 90
            png_compression_level: 6
