imports:
    - { resource: ../config.yml }

# SuluAdmin Configuration
sulu_admin:
    name: "%sulu_admin.name%"
    email: "%sulu_admin.email%"

# SuluDocumentManager Configuration
sulu_document_manager:
    default_session: default
    live_session: live

framework:
    assets:
        json_manifest_path: "%kernel.project_dir%/web/adminV2/manifest.json"
