name: Test Application

on:
    pull_request:
    push:
        branches:
            - master
            - '3.0'

jobs:
    php:
        name: PHP 8.2
        runs-on: ubuntu-latest

        services:
            mysql:
                image: mysql:8.0
                env:
                    MYSQL_ROOT_PASSWORD: 'ChangeMe'
                ports:
                    - 3306:3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3


        steps:
            - name: Checkout project
              uses: actions/checkout@v4

            - name: Install and configure PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.2'
                  extensions: ctype, iconv, mysql, pdo_sqlite
                  coverage: none
                  tools: composer

            - name: Install composer dependencies
              uses: ramsey/composer-install@v3

            - name: Lint code
              run: |
                  bin/adminconsole doctrine:database:create --if-not-exists
                  bin/adminconsole doctrine:schema:create
                  composer lint

            - name: Execute test cases
              run: |
                  composer bootstrap-test-environment
                  composer test

            - name: Test project initialization
              run: bin/console sulu:build dev --destroy

    js-css-website:
        name: Node 20 / Website
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: assets/website

        steps:
            - name: Checkout project
              uses: actions/checkout@v4

            - name: Install and configure Node
              uses: actions/setup-node@v4
              with:
                  node-version: '20'

            - name: Install npm dependencies
              uses: bahmutov/npm-install@v1
              with:
                  working-directory: assets/website

            - name: Lint code
              run: npm run lint

            - name: Test build
              run: npm run build
